### ISSUE TITLE
Can't open gwcli after a pool is deleted

### ISSUE THREAD

**Issue by Jazz9** [ceph/ceph-iscsi-cli#101]
Hello,

I found that gwcli fails to open after I have removed a pool.

[user@server ~]# gwcli
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib64/python2.7/threading.py", line 812, in __bootstrap_inner
    self.run()
  File "/usr/lib64/python2.7/threading.py", line 765, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/usr/lib/python2.7/site-packages/gwcli/storage.py", line 74, in _get_disk_meta
    with cluster_ioctx.open_ioctx(pool) as ioctx:
  File "rados.pyx", line 498, in rados.requires.wrapper.validate_func (/home/jenkins-build/build/workspace/ceph-build/ARCH/x86_64/AVAILABLE_ARCH/x86_64/AVAILABLE_DIST/centos7/DIST/centos7/MACHINE_SIZE/huge/release/12.2.5/rpm/el7/BUILD/ceph-12.2.5/build/src/pybind/rados/pyrex/rados.c:4651)
  File "rados.pyx", line 1193, in rados.Rados.open_ioctx (/home/jenkins-build/build/workspace/ceph-build/ARCH/x86_64/AVAILABLE_ARCH/x86_64/AVAILABLE_DIST/centos7/DIST/centos7/MACHINE_SIZE/huge/release/12.2.5/rpm/el7/BUILD/ceph-12.2.5/build/src/pybind/rados/pyrex/rados.c:12602)
ObjectNotFound: [errno 2] error opening pool 'THEPOOLNAME'

**Comment by mikechristie** [comment]
Did you setup some stuff with gwcli, then delete the pool some of the images were using? Looks like we should add some checks and better handling for that type of thing. I will do a PR for that in a bit.

As a temp workaround I guess you would have do blow away your config by doing:

rados -p rbd rm gateway.conf

then reboot the gateways.

**Comment by Jazz9** [comment]
The pool that was removed did have iscsi images in it. I removed and rebuild config.
