### ISSUE TITLE
gwcli: KeyError rbd_name.split

### ISSUE THREAD

**Issue by discostur** [ceph/ceph-iscsi-cli#154]
Hi,

if you have a ceph pool with dots within the name, gwcli failes with the following error:

```
Warning: Could not load preferences file /root/.gwcli/prefs.bin.
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib64/python2.7/threading.py", line 812, in __bootstrap_inner
    self.run()
  File "/usr/lib64/python2.7/threading.py", line 765, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/usr/lib/python2.7/site-packages/gwcli/storage.py", line 73, in _get_disk_meta
    pool, image = rbd_name.split('.')
ValueError: too many values to unpack

KeyError: u'1234.company.ovirt.lun01'
``` 

Pool Name: 1234.company.ovirt
RBD Image Name: lun01

Greets,
Kilian

**Comment by dillaman** [comment]
There is a warning here [1] that you cannot have periods in your pool or image names. This will be addressed in the newest version of ```ceph-iscsi``` [2] and won't be fixed here.

[1] http://docs.ceph.com/docs/mimic/rbd/iscsi-target-cli/
[2] http://github.com/ceph/ceph-iscsi/
