### ISSUE TITLE
gwcli  TypeError: 'NoneType' object is not iterable

### ISSUE THREAD

**Issue by badeveloper** [ceph/ceph-iscsi-cli#33]
Hello,  
I configure and  run service **rbd-target-api** , but when try run  **gwcli** getting an  error , below **gwcli -d** output:
```
Adding ceph cluster 'ceph' to the UI
Fetching ceph osd information
Querying ceph for state information
Traceback (most recent call last):
  File "/bin/gwcli", line 5, in <module>
    pkg_resources.run_script('gwcli==2.5', 'gwcli')
  File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 540, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 1462, in run_script
    exec_(script_code, namespace, namespace)
  File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 41, in exec_
    exec("""exec code in globs, locs""")
  File "<string>", line 1, in <module>
  File "/usr/lib/python2.7/site-packages/gwcli-2.5-py2.7.egg/EGG-INFO/scripts/gwcli", line 187, in <module>
    
  File "/usr/lib/python2.7/site-packages/gwcli-2.5-py2.7.egg/EGG-INFO/scripts/gwcli", line 93, in main
    
  File "build/bdist.linux-x86_64/egg/gwcli/gateway.py", line 55, in __init__
  File "build/bdist.linux-x86_64/egg/gwcli/ceph.py", line 55, in __init__
  File "build/bdist.linux-x86_64/egg/gwcli/ceph.py", line 141, in __init__
  File "build/bdist.linux-x86_64/egg/gwcli/ceph.py", line 211, in update_state
TypeError: 'NoneType' object is not iterable
```

**Comment by xadhoom76** [comment]
I have the same issue.

**Comment by Jorpilo** [comment]
I am having also the same problem, dont know why...

**Comment by badeveloper** [comment]
Looks like a childish bug , somewhere no handlers for  **None** type...

**Comment by badeveloper** [comment]
I'am was  install latest master branche,   and it solve problem..)))

**Comment by badeveloper** [comment]
Somebody can  check this in own environment??

**Comment by Jorpilo** [comment]
True, now it works great :)
